### ISSUE TITLE
one HSDS instance - one bucket

### ISSUE THREAD

**Issue by untereiner** [HDFGroup/hsds#172]
Hello,

Quick question just to to confirm what i think. Is one instance of an HSDS service connected to one specific bucket ? Is this bucket configured before the instance starts ?

Would it be possible to request data  from a URL like this one: `protocol://resource/sub_path` where: 
- `protocol` stands for s3/azure/etc.
- `resource` the bucket
- `sub_path` the path to the domain

**Comment by jreadey** [comment]
Hi,
   There's a hsds config, BUCKET_NAME, which can be set to a bucket name (or container name for Azure or directory name for posix).  When a request comes in that doesn't otherwise specify a bucket, the default bucket name is used.

   The request can specify a specific bucket by sending a "bucket" query param.

    There's currently no support for one HSDS instance to work with multiple storage accounts - say using S3 or Azure based on the request.  In any case, performance-wise it's best to have HSDS running in the same. region where the storage is located.  If you need this, perhaps you could create a proxy that would forward requests on to specific HSDS instance.

   Let me know if this helps!

**Comment by jreadey** [comment]
Closing issue - @untereiner, please reopen if you have additional questions.
