### ISSUE TITLE
HS_USERNAME assigned admin at startup

### ISSUE THREAD

**Issue by mattjala** [HDFGroup/hsds#379]
The HSDS app startup process sets the 'current user' to the admin user, where current user may be pulled from `UserConfig`, which is in turn populated from the environment. As such, having `HS_USERNAME` set in the environment (as recommended by h5pyd documentation) can result in a different admin user being assigned at HSDS startup, leading to hard to diagnose test failures. 

This might be something to resolve with more consistent documentation about what env vars should be used to provide certain values.

**Comment by jreadey** [comment]
The app.py hs_username and hs_password arguments were added to support a sort of single user mode.  I.e. without any password.txt file or active directory based authentication.  In the workflow script we use the password_file arg, so these aren't needed.  

So maybe an easy fix would be to make a change to app.py so that if password_file is supplied, then hs_username, hs_password args are not passed to HsdsApp in the kwargs.

**Comment by mattjala** [comment]
Resolved in #384 by granting password file precedence; this behavior has usefulness for use of HSDS on demand from h5pyd.
