### ISSUE TITLE
[Question] Some configuration entries must be set as env variables ?

### ISSUE THREAD

**Issue by loichuder** [HDFGroup/hsds#69]
Seeing #50, I thought that I could set all parameters in `config.yml`.

I was however proven wrong when running `runall.sh`. Checks are made on `ROOT_DIR` and `HSDS_ENDPOINT` that therefore must be set as environment variables.

Is this the expected behaviour or am I missing something to use the `root_dir` and `hsds_endpoint` entries in the `config.yml` ?

**Comment by jreadey** [comment]
Hey @loichuder - yes, that's expected.  There are some environment variables like ROOT_DIR that are used by ./runall.sh to determine which docker_compose file to invoke.  E.g. if ROOT_DIR is set, it assumes that you want to use the posix HSDS: https://github.com/HDFGroup/hsds/blob/master/admin/docker/docker-compose.posix.yml.  

Others environment variables like AWS_ACCESS_KEY_ID are not set in config.yml because that would be a security risk to have in a text file.

And finally there are some variables that are by Docker in the compose file rather than accessed by the container.  E.g. "DN_RAM" sets how much memory is allotted to each DN container.

Let me know if you still have questions about this.

**Comment by loichuder** [comment]
I see. 

I indeed want to use the POSIX HSDS. In this case, there is no point setting `root_dir` in `config.yml` as it will be overwritten by `ROOT_DIR` anyway, right ?

**Comment by jreadey** [comment]
Right - the docker-compose.posix.yml needs ROOT_DIR to set the volume mount.

**Comment by jreadey** [comment]
Closing - please re-open if you have questions.
